### ISSUE TITLE
Plugin don't send Test Plan variables

### ISSUE THREAD

**Issue by tobeitgit** [anthonygauthier/jmeter-elasticsearch-backend-listener#101]
I'm trying to send variables as documented [there](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/wiki/Sending-JMeter-variables) but fails to do so when we add them to the User Defined Variables in the Test Plan. They are simply ignored.

![imatge](https://user-images.githubusercontent.com/39725967/103675448-3e073500-4f80-11eb-9f0f-b620a8f271dd.png)

On the other side, it's possible to add variables to the HTTPS samples, **but not the transaction summary sample (what I need)**, when using HTTP Headers, and defining a variable like: "X-es-backend-IP" "${__machineIP}". So, in this case, it's not useful, it should be better in the Test Plan, if it worked.

![imatge](https://user-images.githubusercontent.com/39725967/103675925-c84f9900-4f80-11eb-825e-42a827620cb1.png)

**Comment by clefego** [comment]
How's it going, friends? How do I get the index and dashboard JSON files? I was able to create an index in the ELK and connect it to Grafana, but the data is not arriving in the dashboards. I think there is some small detail missing to resolve. @tobeitgit
