### ISSUE TITLE
Filter exclude is not working

### ISSUE THREAD

**Issue by ramondepieri** [anthonygauthier/jmeter-elasticsearch-backend-listener#103]
When use the "es.sample.filter" with the value !!exclude_this or any other word. Even so is sent to the elastic

**Comment by clefego** [comment]
How's it going, friends? How do I get the index and dashboard JSON files? I was able to create an index in the ELK and connect it to Grafana, but the data is not arriving in the dashboards. I think there is some small detail missing to resolve. @ramondepieri @anthonygauthier

**Comment by clefego** [comment]
Hi @ramondepieri 
 
How do you do?

I'm trying to configure it, but I'm having some problems.
 
How do I get the index JSON files and the Grafana panel?

I was able to create an index in ELK and connect it to Grafana, but the data is not arriving in the dashboards when I run it in Jmeter.

I believe there is a small detail missing to resolve this.

I've already done this process with the InfluxDB plugin, but I'm new to Elasticsearch.

Thanks in advance.
