### ISSUE TITLE
Sending JMeter variables (Custom Fields & Request Header) not working in JMeter version 5.5

### ISSUE THREAD

**Issue by ImtheOneNow** [anthonygauthier/jmeter-elasticsearch-backend-listener#120]
Tried to pass a value to the listener using a field added to the Test Plan User Defined Variables table.  
I also tried to pass the value in the request variable using both the **X-es-backend** method and the method in the screenshot.

Is this a new issue due to the version or the feature never worked with any version?

**Comment by anthonygauthier** [comment]
Hi @dormanb2 ,

It must be an issue with 5.5, I haven't touched JMeter in a while. But I can definitely look into it!

Thanks for the report.

**Comment by ImtheOneNow** [comment]
Hi @anthonygauthier,

Thank you so much.  I'm looking forward to what you are able to find out.

**Comment by sravanthnag** [comment]
Hi @anthony,

I have the same issue and I am using JMeter 5.5. I cannot send any custom data or metrics from the backend listener configuration.

**Comment by ImtheOneNow** [comment]
> Hi @anthony,
> 
> I have the same issue and I am using JMeter 5.5. I cannot send any custom data or metrics from the backend listener configuration.

Hi @sravanthnag, since this never went anywhere (understand people do get busy), I was able to figure out my issue, so I'm here to address your issue hopefully.  I found out that the payload sent to elasticsearch is not stored alphabetically. Take a closer look at the elasticsearch document for your custom data.  Hopefully  this works for you.

**Comment by sravanthnag** [comment]
Hi @ImtheOneNow Thanks for the quick revert. I am able to parse/send custom data when I am trying to send the data using Header manager in the format es-testID. But if I try to put some custom data through user defined variables or the backend listener itself by adding some field like es.testID etc., that is not visible on the elasticsearch.

**Comment by anthonygauthier** [comment]
Sorry I haven't come back to y'all on this. I've been pretty busy with other things and I don't use JMeter on a day-to-day basis anymore so I tend to forget about this plugin 😞 (my bad)!

Essentially, I'd have to check through the User Defined Variables / CSV way of passing variables again 'cause I'm not entirely sure the way it behaves at the moment.

However, as far as the `Header Manager` is concerned, you need to supply the headers with the following format `X-es-backend` as per these lines of code:

https://github.com/anthonygauthier/jmeter-elasticsearch-backend-listener/blob/d837c092f361dc68cd4c885b2fd202ce23b021ba/src/main/java/io/github/delirius325/jmeter/backendlistener/elasticsearch/ElasticSearchMetric.java#L220-L224

**Comment by ImtheOneNow** [comment]
> Sorry I haven't come back to y'all on this. I've been pretty busy with other things and I don't use JMeter on a day-to-day basis anymore so I tend to forget about this plugin 😞 (my bad)!
> 
> Essentially, I'd have to check through the User Defined Variables / CSV way of passing variables again 'cause I'm not entirely sure the way it behaves at the moment.
> 
> However, as far as the `Header Manager` is concerned, you need to supply the headers with the following format `X-es-backend` as per these lines of code:
> 
> https://github.com/anthonygauthier/jmeter-elasticsearch-backend-listener/blob/d837c092f361dc68cd4c885b2fd202ce23b021ba/src/main/java/io/github/delirius325/jmeter/backendlistener/elasticsearch/ElasticSearchMetric.java#L220-L224

Hi @anthonygauthier,

Completely understand.  As I noted in my previous post, it was able to work out my issue.  However, I believe my team and I can use your explanation/solution in the future.  Much appreciated for creating this BackEnd Listener (it saved my bacon 😉)
