### ISSUE TITLE
plugin cannot write to datastream.  response from elasticsearch "only write ops with an op_type of create are allowed in data streams""

### ISSUE THREAD

**Issue by Spoonsk** [anthonygauthier/jmeter-elasticsearch-backend-listener#123]
When using this plugin and attempting to write to a datastream index we get the following response:

```json
{
    "took": 0,
    "ingest_took": 0,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "myindex",
                "_type": "_doc",
                "_id": null,
                "status": 400,
                "error": {
                    "type": "illegal_argument_exception",
                    "reason": "only write ops with an op_type of create are allowed in data streams"
                }
            }
        }
    ]
}
```

this is because datastream indexes only support __write__ operations.  The current code uses an __index__ operation when sending the bulk requests.

Changing this:
`public static String SEND_BULK_REQUEST = "{ \"index\" : { \"_index\" : \"%s\" } }%n";`

To this:
`public static String SEND_BULK_REQUEST = "{ \"create\" : { \"_index\" : \"%s\" } }%n";`

should allow it to support datastream indexes without compromising other functionality

**Comment by anthonygauthier** [comment]
@Spoonsk Thanks for the contribution! I gotta say it's been a while since we've had a PR around here 😅

I'll check it out later on my laptop
