### ISSUE TITLE
Missing Grafana Dashboard file

### ISSUE THREAD

**Issue by subanithak** [anthonygauthier/jmeter-elasticsearch-backend-listener#98]
Documentation says 

* Use either Kibana or Grafana to vizualize your results!
  * [Click here to get a sample Grafana dashboard!](https://github.com/delirius325/jmeter-elasticsearch-backend-listener/wiki/JMeter-Generic-Dashboard) - All you need to do is import it into Grafana and change the data source!

But there is no `wiki/JMeter-Generic-Dashboard` file in the repository.

@delirius325 , Can you please upload the dashboard.

**Comment by clefego** [comment]
How's it going, friends? How do I get the index and dashboard JSON files? I was able to create an index in the ELK and connect it to Grafana, but the data is not arriving in the dashboards. I think there is some small detail missing to resolve.
